
clean_filenames    = true
date_format        = "%Y-%m-%d"
format_dates       = true
ignore_dotfiles    = true
ignore_file_regex  = ''
ignored_files      = []
insert_location    = "before"
match_case_list    = []
overwrite_existing = false
separator          = "ignore"
split_words        = false
stopwords          = []
strip_stopwords    = true
transform_case     = "ignore"
use_synonyms       = false
